db:
  host: ec2-50-17-90-177.compute-1.amazonaws.com
  port: 5432
  user: "ibfrqooufsmidj"
  password: "b6155fbe9644689513853fdda7d91564fb264516606520439b67afb967ff4e9c"
  database: "dfotqnrsmfhq1d"
  sslmode: "require"
smtp:
  username: "chucobo5219@gmail.com"
  password: "bhugudznxheolonw"
  host: "smtp.gmail.com"
  port: "587"
googleoauth:
  clientid: "253768931865-or5h985g6ftkljaeqd8obveq2eod4a2i.apps.googleusercontent.com"
  clientsecret: "8xXEuzZLcpNWrGSahxwjLUo1" 
  redirecturl: "https://amazingtalker.herokuapp.com/googleoauth"
  scopes:
    - "https://www.googleapis.com/auth/userinfo.email"
    - "https://www.googleapis.com/auth/userinfo.profile"
facebookoauth:
  clientid: "3043148599098072"
  clientsecret: "88dd43ba10065f40370ad91c601750d0" 
  redirecturl: "https://amazingtalker.herokuapp.com/facebookoauth"