db:
  host: 0.0.0.0
  port: 5432
  password: "postgres"
  database: "postgres"
  user: "postgres"
  sslmode: "disable"
smtp:
  username: "chucobo5219@gmail.com"
  password: "bhugudznxheolonw"
  host: "smtp.gmail.com"
  port: "587"